services:
  postgres:
    image: postgres:15
    container_name: pos_postgres
    environment:
      POSTGRES_USER: pos_user
      POSTGRES_PASSWORD: pos_pass
      POSTGRES_DB: pos_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
